name: Compose test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  grading:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Autograder
        uses: webtech-network/autograder@bufix/241-GitHub_Module
        with: 
          template-preset : "webdev"
          feedback-type: "default"
          openai-key: ${{ secrets.ENGINE }}
          redis-url: ${{ secrets.REDIS_URL }}
          redis-token: ${{ secrets.REDIS_NAME }}